name: Chronicles Donation Bridge - Game Addon

![common]
>script = pf_donation_protocol
>script = pf_donation_transport
>script = pf_donation_registry
>script = pf_donation_action_add_radiation
>script = pf_donation_action_drop_active_weapon
>script = pf_donation_action_spawn_dogs_3
>script = pf_donation_action_spawn_mutants
>script = pf_donation_action_spawn_npcs
>script = pf_donation_action_spawn_random_hostile_squad
>script = pf_donation_action_spawn_random_mutant_pack
>script = pf_donation_action_change_health
>script = pf_donation_action_invulnerability
>script = pf_donation_action_change_needs
>script = pf_donation_action_spawn_items
>script = pf_donation_action_change_money
>script = pf_donation_action_spawn_anomaly
>script = pf_donation_action_get_drunk
>script = pf_donation_action_trigger_emission
>script = pf_donation_action_sleep_hours
>script = pf_donation_action_drop_outfit
>script = pf_donation_action_damage_equipment
>script = pf_donation_action_drop_random_items
>script = pf_donation_action_teleport_random
>script = pf_donation_action_vehicle
>script = pf_donation_action_explode_nearest_vehicle
>script = pf_donation_action_random_active
>script = pf_donation_action_random_all_presets
>script = pf_donation_runtime
>script = pf_donation_facade
